<?php
return [
   'SERVICES_IDS' => [
      'DIGITAL_FOUNDER' => 1,
      'DIGITAL_GOLD' => 2,
      'DIGITAL_SILVER' => 3,
      'DIGITAL_SILVER_W_ADDON' => 11,
      'DIGITAL_BRONZE' => 4,
      'PRODUCT_FOUNDER' => 12,
      'PRODUCT_GOLD' => 13,
      'PRODUCT_SILVER' => 14,
      'PRODUCT_BRONZE' => 15,
      'VBKIT' => 5,      
   ],
   'PRODUCT_CATS_MAIN' => [   
      'DIGITAL' => 4,
      'DIGITAL_SUB' => 2,
	  'PRODUCT' => 5,
	  'PRODUCT_SPRAY' => 9,
	  'HEALTH' => 21,
	  'WEALTH' => 22,
	  'PROMO_PACK' => 23,
	  'EVENT_PACKS' => 24,
	  'ADDON' => 6,
	  'SUB_ADDON' => 2,
      'VBKIT' => 3,
      'VISIONARY_CUSTOMER_PACKS' => 36,
      'VISIONARY_BUILDER_PACKS' => 38,
      'COURSES' => 25
      
   ],
	'PACK_TYPE' =>[
		'BUNDLE'=>1,
		'CORE'=>2,
		'ESSENTIAL'=>3,
		'PREMIER'=>4
	],
   'PRODUCT_IDS' => [   
      'VBKIT' => 1679,
      'ADDON_PRD_ID' => 33,
      'ADDON_PRD_SUB_ID' => 86,
      'NVULPINT' => 1678,
	  'NVUHW'=>1557,
	  'NVUH'=>1561,
	  'NVU4NS'=>1636,
	  'FL2_APP'=>2114,
	  'FL2_APP_BFX'=>2113,
	  'FL2'=>2116,
	  'VISION_LIFESTYLE'=>2292,
	  'TRADING_APP'=>2172,
	  'DIGITAL_SILVER'=>6,
	  '5_COURSE_BUNDLE'=>2121,
	  '1_COURSE_BUNDLE'=>2123,
     'visionlife'=>2287,
	  '2_COURSE_BUNDLE'=>2122
   ],
   'PRODUCT_FETCH' => [
      'ORDER_TYPE' => 1,
      'SUBS_ORDER_TYPE' => 2,
      'STORE_ID' => 3,
      'AUTOSHIP_STORE_ID' => 5,
      'WHOLESALE_STORE_ID' => 2,
      'DEFAULT_CUSTOMER_TYPE_ID' => 2,
   ],
   "NUMBERS" => ["0"=>0,"1"=>1, "2"=>2, "3"=>3, "4"=>4, "5"=>5, "6"=>6, "7"=>7, "8"=>8, "9"=>9, "10"=>10, 
                 "11"=>11, "12"=>12, "13"=>13, "14"=>14, "15"=>15, "16"=>16, "17"=>17, "18"=>18, "19"=>19, "20"=>20,
                 "21"=>21, "22"=>22, "23"=>23, "24"=>24, "25"=>25, "26"=>26, "27"=>27, "28"=>28, "29"=>29, "30"=>30,
                 "31"=>31, "32"=>32, "33"=>33, "34"=>34, "35"=>35, "36"=>36, "37"=>37, "38"=>38, "39"=>39, "40"=>40,
                 "41"=>41, "42"=>42, "43"=>43, "44"=>44, "45"=>45, "46"=>46, "47"=>47, "48"=>48, "49"=>49, "50"=>50,
                 "51"=>51, "52"=>52, "53"=>53, "54"=>54, "55"=>55, "56"=>56, "57"=>57, "58"=>58, "59"=>59, "60"=>60,
                 "61"=>61, "62"=>62, "63"=>63, "64"=>64, "65"=>65, "66"=>66, "67"=>67, "68"=>68, "69"=>69, "70"=>70,
                 "71"=>71, "72"=>72, "73"=>73, "74"=>74, "75"=>75, "76"=>76, "77"=>77, "78"=>78, "79"=>79, "80"=>80,
                 "81"=>81, "82"=>82, "83"=>83, "84"=>84, "85"=>85, "86"=>86, "87"=>87, "88"=>88, "89"=>89, "90"=>90,
                 "91"=>91, "92"=>92, "93"=>93, "94"=>94, "95"=>95, "96"=>96, "97"=>97, "98"=>98, "99"=>99,"100"=> 100],

   'DEFAULT_PARAMS' => [
	'GUEST_STATUS' => 6,
	'CUSTOMER_TYPE_GUEST' => 6,
	'COUNTRY_CODE' => 'us',
   'COUNTRY_CODE_ES' => 'es',
   'LANGUAGE_CODE_ES' => 'es',
   'COUNTRY_CODE_FR' => 'fr',
   'LANGUAGE_CODE_FR' => 'fr',
	'LANGUAGE_CODE' => 'en',
	'ZERO' => 0,
	'MERCHANTID'=>130,
	'DEFAULT_SMARTSHIP_DATE'=>'28',
	'SERVICEID'=>28,
	'ACCOUNT_DISABLE_STATUS'=>[ 3, 4, 5],// 2 inactive
	'CUSTOMER_TYPE'=>[6],// 6 guest
	'MAXQTY'=>999,
   'DIGITALPLATFORMLINK' => 'https://app.nvisionu.digital/login-loading/?token=',
   'CRYPTOPLATFORMLINK' => 'https://trading-middleware.nvu-dev.com/api/generate-sso?AccessToken=',
   'RGCAADMIN'=>'https://trading-middleware.nvu-dev.com/Validate',
   'RGCAUSER'=>'https://rcga-ui.veryspecialapp.com/login/?token=',
   'office2'=>'https://office2.nvisionu.com/',
   
   ],
   'PRODUCT_TYPES' => [
		'SIMPLE_PRODUCT' => 1,
		'VARIABLE_PRODUCT' => 2,
		'GROUP_PRODUCT' => 3
   ],
   'LOCATION_API' => [
		'IA_API_SERVICE_IP' => 'apapi',
		'IA_API_SERVICE_GEOPLUGIN' => 'geoplugin',
   ],
   'LOCATION_API_URL' => [
		'IP_API_SERVICE_URL' => 'https://pro.ip-api.com/json/',
      'IP_API_KEY'=>'gJZ5hx9pdaOhekt',
		'GEOPLUGIN_SERVICE_URL' => 'http://www.geoplugin.net/php.gp?ip=',
   ],
   'CHECK_IP' => [
		'LOCAL_HOST_IP' => '127.0.0.1',
		'DEFAULT_IP' => '104.93.31.255',
   ],
   'DEFAULT'=>[
		'ERROR_PATH'=>'404',
		'MINIMUM_PRODUCT_REQUIRED_FOR_PACK'=>3,
		'PRODUCT_MAX_QUANTITY'=>100
   ],
   'WEBALIAS'=> [
      'SHORT_CODE'=> '[DISTRIBUTORNAME]'
   ],
   'PRODUCT_STATUS'=>[
      'PUBLISH'=> 'publish',
      'DRAFT'=> 'draft',
   ],
   'CUSTOM_VAT_API'=>[
      'VAT_URL'=> 'https://nvisionu.clientextension.directscale.com/api/CustomApi/GetCustomVatData',
   ],
   'RESPONSE_STATUS_CODE'=>[ 
      'STATUS_200'=>200,
      'STATUS_400'=>400,
   ],
   'CUSTOMER_STATUS_VAL'=>[
		'1'=>'Active',
		'2'=>'Inactive',
		'7'=>'Hold for Review',
		'8'=>'Pending Information',
		'9'=>'Pending VB Req.',
		'10'=>'Corporate Account',
		'11'=>'Test Account',
		'6'=>'Pre Enroll',
		'3'=>'Deleted',
		'4'=>'In Review',
		'5'=>'Canceled'
   ],
   'PRODUCT_SUB_CATS' => [
      'DIGITAL_PACKAGES' => 4,
      'PRODUCT_PACKAGES' => 5,
      'PRODUCT_SPRAY' => 9,
      'HEALTH' => 21,
      'WEALTH_OLD' => 22,
      'PROMO_PACK' => 23,
      'EVENT_PACKS' => 24,
      'COURSES' => 25,
      'ALIVE' =>27,
      'VITAMIN_SPRAY' => 28,
      'VITAMIN_SPRAY_SINGLE' => 29
    ],
    'IFRAME_FETCH' => [
      'STORE_ID' => '4'
    ],
    'STOREIDS'=>[
       'CORPORATE_STORE_ID' => 1,
       'WHOLESALE_STORE_ID' => 2,
       'RETAIL_STORE_ID' => 3,
       'ENROLL_STORE_ID' => 4,
       'AUTOSHIP_STORE_ID' => 5,
       'REWARDS_STORE_ID' => 6,
       'PARTY_STORE_ID' => 7,
       'RETAIL_UPGRADE_STORE_ID' => 8,
       'VOUCHERS_STORE_ID' => 9,
       'BACKOFFICE_STORE_ID' => 10,
       
    ],
	'USER_TYPES'=>[
		"DISTRIBUTOR"=>"1",
		"CUSTOMER"=>"2",
		"GUEST"=>"6",
	],
    'APP_IDS' => [
      'TRADING_APP_ID' => 2172,
    ],
    'STATIC_URLS'=>[
      'NEWACCOUNTMANAGEMENT'=>'account-management-new',
      'nvu-event'=>"nvu-event",
      'fl2-hcp'=>"fl2-hcp",
      'feel-alive-15oz'=>"feel-alive-15oz",
      'feel-alive'=>"feel-alive",
      'visionary-packs'=>"visionary-packs",
      'vision-life-style'=>"vision-life-style",
      'pages_houston-vision-day-event-live-stream'=>"pages/houston-vision-day-event-live-stream",
      "green-tea-extract"=>"green-tea-extract",
      "ginger-root"=>"ginger-root",
      "vitamin-b12"=>"vitamin-b12",
      "fetch-shop-link-connect"=>"fetch-shop-link-connect",      
      "cranberry-extract"=>"cranberry-extract",
      "maca-root"=>"maca-root",
      "spirulina"=>"spirulina",
      "cinnamon-extract"=>"cinnamon-extract",
      "raspberry-ketone"=>"raspberry-ketone",
      "aloe-gel"=>"aloe-gel",
      "apple"=>"apple",
      "beets"=>"beets",
      "cherry"=>"cherry",
      "homepage"=>"homepage",
      "home-new"=>"home-new",
      "login"=>"login",
      "products"=>"products",
      "promotions"=>"promotions",
      "faq"=>"faq",
      "feel-alive"=>"feel-alive",
      "ingredient"=>"ingredient",
      "latam-life-event"=>"latam-life-event",
      "visionary_builder_packs"=>"visionary-builder-packs", 
      "product_bundle"=>"product/bundle",
      "power-7"=>"power-7",
      "pages_feel-alive"=>"pages/feel-alive",
      "alive-foundation"=>"alive-foundation",
      "get-featured-on-magazine"=>"get-featured-on-magazine",
      "alive-challenge"=>"alive-challenge",
      "voucher-20"=>"voucher-20",
      "about-us"=>"about-us",
      "connect"=>"connect",
      "share-your-feedback"=>"share-your-feedback",
      "vision-life-style"=>"vision-life-style",
      "event-ticket"=>"event-ticket",
      "houston-event"=>"houston-event",
      "alive-convention"=>"alive-convention",
      "alive-convention-2024"=>"alive-convention-2024",
      
      "alive-foundation"=>"alive-foundation",
      "live-stream"=>"live-stream",
      "nvu-ingredients"=>"nvu-ingredients",
      "pages_ingredient"=>"pages/ingredient", 
      "houston-vision-day-event-live-stream"=>"houston-vision-day-event-live-stream",
      "30-day-alive"=>"30-day-alive",
      "livestreamingevent"=>" live-streaming-event"
      
     
    ],
    'MASTER_CONSTANTS'=>
    [
      'USER_TYPE1'=>1,
      'USER_TYPE2'=>2,
      'USER_TYPE3'=>3,
      'USER_TYPE4'=>4,
      'USER_TYPE5'=>5,
      'USER_TYPE6'=>6,
      'USER_TYPE7'=>7,  
      'USER_TYPE8'=>8,
      'USER_TYPE9'=>9,
      'USER_TYPE10'=>10,
      'USER_TYPE11'=>11,
    ],
    'KIT_LEVELS' =>[
       'KIT_LEVEL_10' => 10,
       'KIT_LEVEL_20' => 20,
       'KIT_LEVEL_30' => 30,
    ],
    'PRODUCT_TEMPS' =>[
      'DIGITALPROTEMP' => 'digital-product-template',
      'PHYSICALPROTEMP' => 'physical-product-template',
      'ALIVEPROTEMP' => 'alive-product-template',
      'ALIVE2OZPROTEMP' => 'alive2oz-product-template-new',
      'ALIVE2OZABCPROTEMP' => 'alive2oz-product-template-abc',
      'all_section' => 'all_section', 
    ],
    "SLIDERS"=>[
      "TEMP1"=>"1t2bL",
      "TEMP2"=>"2t2bL",
      "TEMP3"=>"3t2bL",
    ],
    "TRAVLE"=>[
      "MAKE_PAYMENT"=>1,
      "CONTACT_SUPPORT"=>0,
      "NOT_EXPIERED"=>2,
    ]
    
      
];
